### ISSUE TITLE
老哥 报这个错是啥问题啊

### ISSUE THREAD

**Issue by jimtan2015** [gstory0404/flutter_pangrowth#11]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningDebug'.
> Keystore file not set for signing config config

[✓] Flutter (Channel stable, 3.7.3, on macOS 11.6.1 20G224 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by gstory0404** [comment]
android密钥不存在，https://github.com/gstory0404/flutter_pangrowth/blob/master/example/android/app/build.gradle 中移除signingConfig signingConfigs.config 或者写入自己的key @jimtan2015
