### ISSUE TITLE
混淆配置是不是有问题啊，release包的时候报错了

### ISSUE THREAD

**Issue by zytabcd123** [gstory0404/flutter_pangrowth#2]
R8: com.android.tools.r8.errors.b: Attribute Signature requires InnerClasses attribute. Check -keepattributes directive.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
Running Gradle task 'assembleRelease'...                           45.0s
[!] The shrinker may have failed to optimize the Java bytecode.
    To disable the shrinker, pass the `--no-shrink` flag to this command.
    To learn more, see: https://developer.android.com/studio/build/shrink-code
Gradle task assembleRelease failed with exit code 1

这是我的打包配置
![image](https://user-images.githubusercontent.com/11885452/147182651-c1be1189-a2ed-4141-bb4b-31c755ddd468.png)

**Comment by gstory0404** [comment]
使用的插件版本是多少

**Comment by zytabcd123** [comment]
1.0.1

**Comment by gstory0404** [comment]
都改为false关闭混淆 打包尝试一下

**Comment by zytabcd123** [comment]
关闭混淆可以打包的，但是我这项目需要开启混淆

**Comment by gstory0404** [comment]
classpath 'com.android.tools.build:gradle:4.1.0'
看下你的多少

**Comment by zytabcd123** [comment]
classpath 'com.android.tools.build:gradle:4.1.0'

**Comment by gstory0404** [comment]
我这边测试打包正常 体验demo就是打包release。目前推测可能是方法超过上限导致，可以尝试Dex分包处理

**Comment by zytabcd123** [comment]
从穿山甲的demo里面找到的，混淆配置里面加上这个就可以了。

#保护内部类
-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,EnclosingMethod

**Comment by gstory0404** [comment]
> 从穿山甲的demo里面找到的，混淆配置里面加上这个就可以了。
> 
> #保护内部类
> -keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,EnclosingMethod

好的 后续我添加一下
