### ISSUE TITLE
ios编译失败

### ISSUE THREAD

**Issue by xiaochonzi** [gstory0404/flutter_pangrowth#3]
fatal error: 'controller/GridVideoViewController.h' file not found。

**Comment by gstory0404** [comment]
清理缓存 重新拉取编译试一下

**Comment by xiaochonzi** [comment]
@gstory0404  你好，我看了ios那块的源码，好像就是没有这个文件。

**Comment by gstory0404** [comment]
> @gstory0404 你好，我看了ios那块的源码，好像就是没有这个文件。

更新1.0.3尝试一下
