### ISSUE TITLE
java.lang.NullPointerException: factory() must not be null

### ISSUE THREAD

**Issue by wangpeishihang** [gstory0404/flutter_pangrowth#4]
![image](https://user-images.githubusercontent.com/24558232/158944430-1348c75e-d921-409c-bffc-5c11b891da35.png)

**Comment by wangpeishihang** [comment]
请问一下作者，我安卓出现这个问题怎么解决啊，我ios可以正常使用

**Comment by gstory0404** [comment]
> 请问一下作者，我安卓出现这个问题怎么解决啊，我ios可以正常使用

SDK初始化失败 或者 未进行初始化

**Comment by wangpeishihang** [comment]
> > 请问作者，我安卓出现这个问题怎么解决啊，我的ios可以正常使用了
> 
> SDK初始化 或者未进行初始化

这个sdk初始化不是只要初始化flutter_unionad这个插件九可以了吗，然后使用的时候直接
![image](https://user-images.githubusercontent.com/24558232/158951953-21eb6b35-d526-456c-beda-54487665824a.png)
这样写就可以了吗？

**Comment by gstory0404** [comment]
> > > 请问作者，我安卓出现这个问题怎么解决啊，我的ios可以正常使用了
> > 
> > 
> > SDK初始化 或者未进行初始化
> 
> 这个sdk初始化不是只要初始化flutter_unionad这个插件九可以了吗，然后使用的时候直接 ![image](https://user-images.githubusercontent.com/24558232/158951953-21eb6b35-d526-456c-beda-54487665824a.png) 这样写就可以了吗？

[novel](https://github.com/gstory0404/flutter_pangrowth/blob/branch_video/novel.md)     [video](https://github.com/gstory0404/flutter_pangrowth/blob/branch_video/video.md) 查看一下使用方法 初始化

**Comment by gstory0404** [comment]
@wangpeishihang flutter_unionad初始化成功 然后初始化video，就可以使用video中的方法

**Comment by wangpeishihang** [comment]
我unionad已经初始化成功了，然后使用初始化video就会卡在开始初始化，然后就没有然后了，这是什么地方配置错了吗



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 18, 2022 18:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gstory0404/flutter_pangrowth] java.lang.NullPointerException:factory() must not be null (Issue #4)




 
@wangpeishihang flutter_unionad初始化成功 然后初始化video，就可以使用video中的方法
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gstory0404** [comment]
@wangpeishihang 初始化video可以查看下log日志

**Comment by wangpeishihang** [comment]
已经解决了，与其说解决了不如说莫名其妙好了，就是
在dependencies中添加
implementation 'com.bytedance.applog:RangersAppLog-Lite-cn:6.2.2'

然后就好了
