### ISSUE TITLE
找不到依赖包

### ISSUE THREAD

**Issue by bingoming** [gstory0404/flutter_pangrowth#5]
flutter_pangrowth:debugCompileClasspath'.
   > Could not find com.bytedance.applog:RangersAppLog-Lite-cn:6.8.0.
     Required by:
         project :flutter_pangrowth > com.pangle.cn:pangrowth-sdk:2.2.0.1
         project :flutter_pangrowth > com.pangle.cn:partner-luckycat-api-sdk:2.2.0.1
   > Could not find com.volcengine:apm_insight_sdk:1.0.3.
     Required by:
         project :flutter_pangrowth > com.pangle.cn:pangrowth-sdk:2.2.0.1
   > Could not find com.volcengine:apm_insight_crash:1.4.2.
     Required by:
         project :flutter_pangrowth > com.pangle.cn:pangrowth-sdk:2.2.0.1
   > Could not find org.chromium.net:cronet:4.0.27.1-rc.4-tob.
     Required by:
         project :flutter_pangrowth > com.pangle.cn:partner-luckycat-api-sdk:2.2.0.1
   > Could not find com.bytedance.frameworks.baselib:ttnet:4.0.27.1-rc.4-tob.
     Required by:
         project :flutter_pangrowth > com.pangle.cn:partner-luckycat-api-sdk:2.2.0.1

**Comment by gstory0404** [comment]
> https://github.com/gstory0404/flutter_pangrowth/issues/4#issuecomment-1073523971

尝试下 引入这个包

**Comment by gstory0404** [comment]
#4 
尝试在dependencies中添加
implementation 'com.bytedance.applog:RangersAppLog-Lite-cn:6.2.2'

**Comment by bingoming** [comment]
我是个呆瓜
没有看接入文档
