### ISSUE TITLE
添加gradle脚本后构建异常

### ISSUE THREAD

**Issue by bingoming** [gstory0404/flutter_pangrowth#6]
![image](https://user-images.githubusercontent.com/30516379/165880927-5a301df1-3418-41e9-8c34-e3303a1cb2e9.png)

报错文件
![1651202522(1)](https://user-images.githubusercontent.com/30516379/165880977-e6224ad8-955d-4d2d-b7e3-9ffeab54415c.jpg)

去掉apply from: 'https://sf3-fe-tos.pglstatp-toutiao.com/obj/pangle-empower/android/pangrowth_media/plugin_config.gradle'后正常构建. 此时的AndroidManifest文件:
![1651202586(1)](https://user-images.githubusercontent.com/30516379/165881124-cdc2281d-3a25-4cd8-b71a-b3a1e4da00dc.jpg)

**Comment by bingoming** [comment]
android:label乱码问题  改英文可以正常构建

**Comment by gstory0404** [comment]
查看 android/app/src/main/AndroidManifest.xml下是否有 tools:replace="android:label"

**Comment by bingoming** [comment]
![image](https://user-images.githubusercontent.com/30516379/165884889-5b781260-a043-46d1-bf46-3a6bbd30cd54.png)
有

**Comment by gstory0404** [comment]
这个插件没有使用，这边测试正常，可以向官方提交工单资讯下

**Comment by bingoming** [comment]
在下面两处地方加上编码格式
AndroidManifest.xml
![image](https://user-images.githubusercontent.com/30516379/166873251-37c7e893-342b-4c28-bb2e-1c9ca7b35a5c.png)
gradle.properties
![image](https://user-images.githubusercontent.com/30516379/166873284-1b72f2e4-f86e-4f3d-8854-e8a727fbfd8b.png)
